site_name: OpenDSM
site_url: !ENV [SITE_URL, "https://opendsm.energy/"]
dev_addr: 127.0.0.1:8000
# repo_url: https://github.com/opendsm/opendsm

docs_dir: "src"
extra_css:
  - "css/custom.css"
  
plugins:
  - search
  - blog:
      blog_dir: community/working_group_updates
      post_dir: "{blog}/posts"
      post_url_format: "{date}/{slug}"
      archive: true
      categories: false
      authors: false
      pagination_per_page: 10
  - awesome-nav
  - macros
  - section-index
  - site-urls:
      attributes:
        - src
        - href
        - data
        - data-src
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            show_bases: false
            show_if_no_docstring: true
            show_root_heading: false
            show_root_toc_entry: false
            show_source: false
            inherited_members: true
            members_order: source
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_docstring_modules: false
            docstring_section_style: table
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
      fallback_to_build_date: true
      exclude:
        - index.md
        - install.md
        - community.md
        - documentation/index.md
        - documentation/eemeter/index.md
        - documentation/drmeter/index.md

theme:
  name: "material"
  language: en
  custom_dir: "src/overrides"

  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: "https://opendsm.github.io/opendsm-website/assets/images/common/opendsm-icon-white.svg"

  features:
    - content.code.copy
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky       # top row of tabs sticks to the top of the page
    # - navigation.expand            # default expand all tabs
    # - navigation.prune
    # - navigation.path
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest
    - content.footnote.tooltips
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: 🔗
  - sane_lists
  - smarty
  - md_in_html
  # consider adding fancylists for sufficiency?

extra:
  generator: false
  version:
    provider: mike
    default: latest

extra_javascript:
  # - https://cmp.osano.com/16A0DbT9yDNIaQkvZ/af2b9f1f-3ac7-4a18-a99a-e487d04f08e6/osano.js?variant=two  # loaded in extrahead instead
  - javascripts/mathjax.js  # For local MathJax configuration
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # For MathJax CDN
  - javascripts/version-selector.js  # Moves the version selector right, next to the palette toggle

copyright: Copyright © OpenDSM a Series of LF Projects, LLC<br>
  For web site terms of use, trademark policy and other project policies please see <a href="https://lfprojects.org">https://lfprojects.org</a>.