site_name: OpenDSM
site_url: !ENV [SITE_URL, "https://opendsm.energy/"]
dev_addr: 127.0.0.1:8000

docs_dir: "src"
extra_css:
  - "css/custom.css"
  
plugins:
  - search
  - macros
  - section-index
  - site-urls:
      attributes:
        - src
        - href
        - data
        - data-src
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            show_bases: false
            show_if_no_docstring: true
            show_root_heading: false
            show_root_toc_entry: false
            show_source: false
            inherited_members: true
            members_order: source
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_docstring_modules: false
            docstring_section_style: table

nav:
  - Home: index.md
  - Install: install.md
  - Documentation:
    - documentation/index.md
    - History: documentation/history.md
    - Philosophy: documentation/philosophy.md
    - General Concepts: documentation/general_concepts.md
    - OpenEEmeter: 
      - documentation/eemeter/index.md
      - Hourly Model:
        - Methodology: documentation/eemeter/hourly_model/methodology.md
        - Example: documentation/eemeter/hourly_model/example.md
        - API: documentation/eemeter/hourly_model/api.md
        - References: documentation/eemeter/hourly_model/references.md
      - Daily Model: 
        - Methodology: documentation/eemeter/daily_model/methodology.md
        - Example: documentation/eemeter/daily_model/example.md
        - API: documentation/eemeter/daily_model/api.md
        - References: documentation/eemeter/daily_model/references.md
      - Billing Model: 
        - Methodology: documentation/eemeter/billing_model/methodology.md
        - Example: documentation/eemeter/billing_model/example.md
        - API: documentation/eemeter/billing_model/api.md
        - References: documentation/eemeter/billing_model/references.md
    - DRmeter:
      - documentation/drmeter/index.md
      - CalTRACK Model: 
        - Methodology: documentation/drmeter/caltrack_model/methodology.md
        - Example: documentation/drmeter/caltrack_model/example.md
        - API: documentation/drmeter/caltrack_model/api.md
        - References: documentation/drmeter/caltrack_model/references.md
      - New Model: documentation/drmeter/new_model/index.md
  - Community: community.md

theme:
  name: "material"
  logo: "https://opendsm.github.io/opendsm-website/assets/images/common/opendsm-icon-white.svg"
  features:
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - search.suggest
  
  language: en

  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mod
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: 
  - footnotes
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - sane_lists

extra:
  generator: false

extra_javascript:
  - https://cmp.osano.com/16A0DbT9yDNIaQkvZ/af2b9f1f-3ac7-4a18-a99a-e487d04f08e6/osano.js?variant=two

copyright: Copyright © OpenDSM a Series of LF Projects, LLC<br>
  For web site terms of use, trademark policy and other project policies please see <a href="https://lfprojects.org">https://lfprojects.org</a>.