[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "opendsm-website-prerelease"
version = "0.1.0"
description = "Website prerelease for OpenDSM"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }
authors = [{ name = "opendsm", email = "opendsm@lists.lfenergy.org" }]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

dependencies = [
  "griffe==1.14.0",
  "mkdocs==1.6.1",
  "mkdocs-autorefs==1.4.3",
  "mkdocs-awesome-nav==3.2.0",
  "mkdocs-get-deps==0.2.0",
  "mkdocs-git-revision-date-localized-plugin==1.4.7",
  "mkdocs-macros-plugin==1.3.9",
  "mkdocs-material==9.6.20",
  "mkdocs-material-extensions==1.3.1",
  "mkdocs-material[imaging]",
  "mkdocs-section-index==0.3.10",
  "mkdocs-site-urls==0.3.1",
  "mkdocstrings==0.30.0",
  "mkdocstrings-python==1.18.2",
  "pymdown-extensions==10.15",
  "opendsm @ git+https://github.com/opendsm/opendsm@master",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src"]  # Adjust if your importable package is elsewhere

[project.urls]
Homepage = "https://lfenergy.org/projects/opendsm"
Documentation = "https://opendsm.energy"
Repository = "http://github.com/opendsm/opendsm"
Issues = "http://github.com/opendsm/opendsm/issues"